/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright © 2026 The Halo Archive */
use crate::{
    adapters::{
        coating::{
            extract_coating_globals, extract_material_coatings, extract_runtime_coatings,
            extract_styles,
        },
        customization::{extract_customization, extract_visors},
        forge::extract_forge,
        material::extract_materials,
        model::extract_models,
        scenario::extract_scenario,
        texture::extract_texture,
    },
    utils::{get_strings, get_tags, load_modules},
};
use ekur_definitions::{
    coating_swatch::CoatingSwatchPODTag, material_palette::MaterialPaletteTag,
    material_swatch::MaterialSwatchTag, model::ModelDefinition,
};

use anyhow::Result;
use clap::Parser;

mod adapters;
mod utils;

const MODEL_GROUP: &str = "hlmt";
const PALETTE_GROUP: &str = "mwpl";
const MATERIAL_SWATCH_GROUP: &str = "mwsw";
const COATING_SWATCH_GROUP: &str = "cmsw";

#[derive(Debug, Parser)]
struct EkurArgs {
    #[clap(short, long)]
    /// The path leading to the deploy folder of a Halo Infinite installation.
    module_path: String,
    #[clap(long)]
    /// The path to save the files generated by Ekur into.
    save_path: String,
    #[clap(long)]
    /// The path to the strings.txt file from the ReclaimerFiles repository.
    strings_path: String,
    #[clap(short, long, default_value = "false")]
    /// Whether to ignore extracting bitmaps or not.
    skip_bitmaps: bool,
    #[clap(short, long, default_value = "false")]
    /// Whether the deploy files are from a campaign installation or not.
    is_campaign: bool,
}

fn main() -> Result<()> {
    let args = EkurArgs::parse();
    let save_path = &args.save_path;
    let strings = get_strings(&args.strings_path)?;
    let mut modules = load_modules(&args.module_path)?;

    // Used in: customization, forge, models
    let mode_tags = get_tags::<ModelDefinition>(&MODEL_GROUP, &mut modules)?;
    // Used in: forge, material coating
    let mwpl_tags = get_tags::<MaterialPaletteTag>(&PALETTE_GROUP, &mut modules)?;
    // Used in: forge, material coating, visor
    let mwsw_tags = get_tags::<MaterialSwatchTag>(&MATERIAL_SWATCH_GROUP, &mut modules)?;
    // Used in: coating globals, runtime
    let cmsw_tags = get_tags::<CoatingSwatchPODTag>(&COATING_SWATCH_GROUP, &mut modules)?;

    let textures = extract_materials(&mut modules, save_path, args.is_campaign)?;
    if !args.is_campaign {
        extract_customization(&mut modules, &mode_tags, &strings, save_path)?;
        extract_forge(&mut modules, &mode_tags, &mwpl_tags, &mwsw_tags, save_path)?;
    }

    extract_models(&mut modules, &strings, save_path)?;
    extract_scenario(&mut modules, save_path)?;
    extract_visors(&mut modules, &mwsw_tags, save_path)?;
    extract_coating_globals(&mut modules, &cmsw_tags, save_path)?;
    extract_styles(&mut modules, &strings, save_path)?;
    extract_runtime_coatings(&mut modules, &cmsw_tags, save_path)?;
    extract_material_coatings(&mut modules, &mwpl_tags, &mwsw_tags, &strings, save_path)?;
    if !args.skip_bitmaps {
        extract_texture(&mut modules, textures, &cmsw_tags, &mwsw_tags, save_path)?;
    }
    Ok(())
}
