mod banished_metal;
mod color_decal;
mod common_utils;
mod const_decal;
mod decal_mp;
mod diffuse_shader;
mod layered_shader;
mod parallax_decal;
pub mod process_material;
mod self_illum;
pub mod serde_definitions;
