/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright © 2025 Surasia */
pub mod bitmap;
pub mod coating_globals;
pub mod coating_swatch;
pub mod crate_block;
pub mod customization_globals;
pub mod equipment;
pub mod forge_globals;
pub mod forge_manifest;
pub mod forge_object_definition;
pub mod material;
pub mod material_palette;
pub mod material_styles;
pub mod material_swatch;
pub mod model;
pub mod object_attachment;
pub mod object_theme;
pub mod particle_model;
pub mod render_model;
pub mod runtime_geo;
pub mod runtime_style;
pub mod runtime_styles;
pub mod scenario;
pub mod scenery;
pub mod stringlist;
pub mod vehicle;
pub mod visor;
pub mod weapon;
